#!/bin/sh
chown root:root /usr/local/sbin/updatesnotify
chown root:root /usr/local/sbin/updatesnotify-launcher
chown -R root:root /usr/share/lite-updatesnotify
chown root:root /usr/share/applications/lite-updatesnotify.desktop